[versions]
kotlin = "2.2.21"
kotlinx-coroutines = "1.10.2"
kotlin-logging = "7.0.7"
okio = "3.16.2"
kotest = "6.0.3"
kotest-bdd = "2.1.3"
kotlin-gen = "1.0.2"
ksp = "2.2.20-2.0.3"
vanniktechMavenPublish = "0.34.0"
dokka = "2.1.0"
gradle-publish = "2.0.0"
ktembed = "0.0.2"
ktor = "3.3.0"
ktml = "0.1.10"
korge = "6.0.0"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging", version.ref = "kotlin-logging" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-fakefilesystem = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
ktool-kotest-bdd = { module = "dev.ktool:kotest-bdd", version.ref = "kotest-bdd" }
ktool-kotlin-gen = { module = "dev.ktool:kotlin-gen", version.ref = "kotlin-gen" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktml-runtime = { module = "dev.ktml:ktml-runtime", version.ref = "ktml" }
ktml-ktor = { module = "dev.ktml:ktml-ktor", version.ref = "ktml" }
ktembed-runtime = { module = "dev.ktool:ktembed-runtime", version.ref = "ktembed" }
korge-compression = { module = "com.soywiz:korlibs-compression", version.ref = "korge" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotest = { id = "io.kotest", version.ref = "kotest" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechMavenPublish" }
gradle-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-publish" }
ktembed = { id = "dev.ktool.ktembed", version.ref = "ktembed" }
ktml = { id = "dev.ktml.gradle", version.ref = "ktml" }
